### ISSUE TITLE
Osa 2: Komponenttien lifecycle-metodit

### ISSUE THREAD

**Issue by Sose** [fullstackopen/fullstackopen.github.io#42]
Osassa 2 puhutaan hieman epäselvästi ristiin metodeista `componentDidMount` ja `componentWillMount`. Githubin mallikoodissa on käytetty williä, mutta materiaalin koodiesimerkissä on hämmentävästi

```
  componentDidMount() {
    console.log('will mount')
```

En tiedä, että onko ihan sama kumpaa käyttää tai miten tekstiä pitäisi muokata, mutta vähän epäselvää on tällä hetkellä.

**Comment by JuhQ** [comment]
Samaa mieltä että nyt vähän epäselvä.
`componentWillMount` ajetaan ennen kuin komponentti on liitetty domiin.
`componentDidMount` ajetaan sen jälkeen kun komponentti on liitetty domiin.

Haluatko tehdä pr:n tästä? :)

**Comment by Sose** [comment]
Tein pienen pr:n. 

Kävin lukemassa https://reactjs.org/docs/react-component.html#unsafe_componentwillmount ja sain sen käsityksen, että `componentDidMount` on nimenomaan oikea paikka esim. tehdä AJAX-kyselyjä?

Silti kuitenkin mallikoodi https://github.com/FullStack-HY/part2-notes/blob/part2-4/src/App.js#L36 käyttää `componentWillMount`-metodia (ei näköjään masterissa, mutta tuossa tagissa kyllä). Kenties sekin pitäisi muuttaa?

**Comment by mluukkai** [comment]
Did tosiaan oikea. Materiaalissa ei pitäisi olla mainitaa will:istä. 

Mallikoodin modaaminen on hieman hankalampaa, koska siinä on niin monta tagia, mihin se pitäisi myös saada. Jos joku jaksaisi modata gitin historiaa niin oisin kiitollinen. Itse en todennäk ehdi ainakaan ihan heti sitä tekemään.
